{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templating-deep-dive.fullname" . }}
  labels:
    {{- include "templating-deep-dive.selectorLabels" . | nindent 4 }}
spec:
  type: {{.Values.service.type }}
  selector:
    {{- include "templating-deep-dive.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{.Values.service.port }}
      targetPort: {{.Values.containerPort.http }}
{{end}}