apiVersion: v1
kind: ConfigMap
metada:
  name: {{ include "accessing-files.fullname" . }}
data:
{{- range $path, $_ := .Files.Glob "files/*.properties" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{ end }}