CustomName: ''

replicaCount: 2

environment: production

image:
  name: nginx
  tag: "1.27.0"

containerPort:
  http: 80

services:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 3007

securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 2000